"""goals table

Revision ID: 5757e551a7ea
Revises: e35206e235a4
Create Date: 2026-05-23 23:35:22.663174

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5757e551a7ea"
down_revision: Union[str, Sequence[str], None] = "e35206e235a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "goals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("target_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("current_amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column(
            "status", sa.Enum("IN_PROGRESS", "COMPLETED", name="goal_status"), nullable=False
        ),
        sa.CheckConstraint(
            "current_amount >= 0", name=op.f("ck_goals_ck_goals_current_non_negative")
        ),
        sa.CheckConstraint("target_amount > 0", name=op.f("ck_goals_ck_goals_target_positive")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_goals_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_goals")),
    )
    op.create_index(op.f("ix_goals_user_id"), "goals", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_goals_user_id"), table_name="goals")
    op.drop_table("goals")
    # ### end Alembic commands ###
